### ISSUE TITLE
Incompatible with Node 4

### ISSUE THREAD

**Issue by vitaly-t** [parro-it/private-class#1]
The `...` operand makes it incompatible with Node 4.x, which would otherwise work fine.

That operand is easy to replace with traditional concatenation.

Otherwise very good work!

I'm trying to understand though, how it would work with derivation, i.e. using `extend` on classes. Any idea? An example would be great ;)

**Comment by parro-it** [comment]
> The ... operand makes it incompatible with Node 4.x, which would otherwise work fine.

> That operand is easy to replace with traditional concatenation.

That's fine for me if you mind doing a PR , but I'm not interested in implementing it myself.

> I'm trying to understand though, how it would work with derivation, i.e. using extend on classes. Any idea? An example would be great ;)

What your doubts exactly?

**Comment by vitaly-t** [comment]
If we have classes:

```js
class BaseClass {
}

class ClassA extends BaseClass {
}

class ClassB extends ClassA {
}
```

How do we set private properties in each of these classes using your library? I'm having difficulty figuring out the correct declaration with your library here.

**Comment by parro-it** [comment]
> How do we set private properties in each of these classes using your library? I'm having difficulty figuring out the correct declaration with your library here.

It depends, if you want only to hide private state from the extern, you can simply do :

```js
class BaseClass {
}

class ClassA extends BaseClass {
}

class ClassB extends ClassA {
}

export priv(ClassA);
export priv(ClassB);
```

Instead, if you want that private stuff is only visible in the class that declare it:

```js
class BaseClass {
}

class ClassA extends  priv(BaseClass) {
}

class ClassB extends  priv(ClassA) {
}

export ClassA;
export ClassB;
```

**Comment by vitaly-t** [comment]
@parro-it Thanks so much!

Still I think that supporting Node 4.x is a good idea ;)

**Comment by parro-it** [comment]
> Still I think that supporting Node 4.x is a good idea ;)
Do a PR if you want ...
